aws_app_access_key     = "<ACCESS_KEY>"
aws_app_access_token   = "<SECRET_ACCESS_KEY>"
k8s_cluster_name       = "<CLUSTER_NAME>"
aws_profile            = "<PROFILE>"
region                 = "<REGION>"